export const ButtonType = {
	PRIMARY_MEDIUM_DEFAULT: 'primary-medium-default',
	PRIMARY_MEDIUM_DEFAULT_DISABLED: 'primary-medium-default-disabled',
	SECONDARY_MEDIUM_DEFAULT: 'secondary-medium-default',
	SECONDARY_MEDIUM_DEFAULT_DISABLED: 'secondary-medium-default-disabled',
	MEDIUM_OUTLINE_DEFAULT: 'medium-outline-default',
	MEDIUM_OUTLINE_DEFAULT_DISABLED: 'medium-outline-default-disabled',
	MEDIUM_GHOST_DEFAULT: 'medium-ghost-default',
	MEDIUM_GHOST_DEFAULT_DISABLED: 'medium-ghost-default-disabled',
	PRIMARY_LARGE_DEFAULT: 'primary-large-default',
	PRIMARY_LARGE_DEFAULT_DISABLED: 'primary-large-default-disabled',
	SECONDARY_LARGE_DEFAULT: 'secondary-large-default',
	SECONDARY_LARGE_DEFAULT_DISABLED: 'secondary-large-default-disabled',
	LARGE_OUTLINE_DEFAULT: 'large-outline-default',
	LARGE_OUTLINE_DEFAULT_DISABLED: 'large-outline-default-disabled',
	LARGE_GHOST_DEFAULT: 'large-ghost-default',
	LARGE_GHOST_DEFAULT_DISABLED: 'large-ghost-default-disabled',
	PRIMARY_MEDIUM_DEFAULT_NOTICE: 'primary-medium-default-notice',
	PRIMARY_MEDIUM_DEFAULT_NOTICE_ACTIVE: 'primary-medium-default-notice-active',
};
