export const Svgs = {
	DOWN_ARROW: 'downArrow',
	SIDEBAR_ICON: 'sidebarIcon',
	RIGHT_ARROW: 'rightArrow',
	PIE_CHART: 'pieChart',
	PIE_CHART_DARK: 'pieChartDark',
	OPEN_BOOK: 'openBook',
	ARROW_RISE: 'arrowRise',
	ARROW_FALL: 'arrowFall',
	RECTANGLE: 'rectangle',

	DATA_LOADING_VIEW_1: 'dataLoadingView1',
	DATA_LOADING_VIEW_2: 'dataLoadingView2',
	SEARCH_BOX: 'searchBox',
	SEARCH_BOX_CANCEL: 'searchBoxCancel',
	SEARCH_DUMMY: 'SearchDummy',
	SEARCH_DUMMY_CANCEL: 'SearchDummyCancel',
	DEFAULT_BELL_ICON: 'DefaultBellIcon',

	LINE_ICON: 'lineIcon',
	MESSAGE_ICON: 'messageIcon',
	CALL_ICON: 'callIcon',
	LOCATION_ICON: 'loactionIcon',
	LOGO: 'Logo',
	TEACHER: 'Teacher',
	CHECK: 'check',
	WARNING: 'warning',
	DOUBLE_TICK: 'doubleTick',
	ELLIPSE: 'ellipse',
	ELLIPSE1: 'ellipse1',
	ARROW_LEFT: 'arrowLeft',
	DOUBLE_ARROW: 'doubleArrow',
	CREATE_PENCIL: 'createPencil',
	ARROW: 'arrow',
	CALENDER: 'calender',
};
