const noticeArray = [
	{
		title: 'Up-Coming Vacation',
		msg: 'Causae eripuit sententiae at eam, volumus adipiscing liberavisse duo ad. Has wisi invenire ei, ut qui parte.....',
		summary: `Causae eripuit sententiae at eam, volumus adipiscing liberavisse duo ad.Has wisi invenire ei, ut qui parte. someday there are going to be holidaysdsd someday there are going to be holidaysdsd someday there are going to someday there are going to be holidaysdsd someday there are going to be holidaysdsd someing to be theholidaysdsd someday there are going to be holidaysdsd someday there are going to be holidaysdsd`,
		publish_date: '04/08/23',
		readed: true,
		noticeStatus: 'New',
		type: 'published',
	},
	{
		title: 'Up-Coming Vacation',
		msg: 'Causae eripuit sententiae at eam, volumus adipiscing liberavisse duo ad. Has wisi invenire ei, ut qui parte.....',
		summary: `Causae eripuit sententiae at eam, volumus adipiscing liberavisse duo ad.Has wisi invenire ei, ut qui parte. someday there are going to be holidaysdsd someday there are going to be holidaysdsd someday there are going to someday there are going to be holidaysdsd someday there are going to be holidaysdsd someing to be theholidaysdsd someday there are going to be holidaysdsd someday there are going to be holidaysdsd`,
		publish_date: '04/08/23',
		readed: true,
		noticeStatus: 'New',
		type: 'published',
	},
	{
		title: 'Up-Coming Vacation',
		msg: 'Causae eripuit sententiae at eam, volumus adipiscing liberavisse duo ad. Has wisi invenire ei, ut qui parte.....',
		summary: `Causae eripuit sententiae at eam, volumus adipiscing liberavisse duo ad.Has wisi invenire ei, ut qui parte. someday there are going to be holidaysdsd someday there are going to be holidaysdsd someday there are going to someday there are going to be holidaysdsd someday there are going to be holidaysdsd someing to be theholidaysdsd someday there are going to be holidaysdsd someday there are going to be holidaysdsd`,
		publish_date: '04/08/23',
		readed: true,
		noticeStatus: 'New',
		type: 'published',
	},
	{
		title: 'Up-Coming Vacation',
		msg: 'Causae eripuit sententiae at eam, volumus adipiscing liberavisse duo ad. Has wisi invenire ei, summary:`Causae eripuit sententiae at eam, volumus adipiscing liberavisse duo ad.Has wisi invenire ei, ut qui parte. someday there are going to be holidaysdsd someday there are going to be holidaysdsd someday there are going to someday there are going to be holidaysdsd someday there are going to be holidaysdsd someing to be theholidaysdsd someday there are going to be holidaysdsd someday there are going to be holidaysdsd`,ut qui parte.....',
		publish_date: '04/08/23',
		readed: true,
		noticeStatus: 'New',
		type: 'published',
	},
	{
		title: 'Up-Coming Vacation',
		msg: 'Causae eripuit sententiae at eam, volumus adipiscing liberavisse duo ad. Has wisi invenire ei, ut qui parte.....',
		summary: `Causae eripuit sententiae at eam, volumus adipiscing liberavisse duo ad.Has wisi invenire ei, ut qui parte. someday there are going to be holidaysdsd someday there are going to be holidaysdsd someday there are going to someday there are going to be holidaysdsd someday there are going to be holidaysdsd someing to be theholidaysdsd someday there are going to be holidaysdsd someday there are going to be holidaysdsd`,
		publish_date: '04/08/23',
		readed: true,
		noticeStatus: 'Expiring soon',
		type: 'approved',
	},
	{
		title: 'Up-Coming Vacation',
		msg: 'Causae eripuit sententiae at eam, volumus adipiscing liberavisse duo ad. Has wisi invenire ei, ut qui parte.....',
		summary: `Causae eripuit sententiae at eam, volumus adipiscing liberavisse duo ad.Has wisi invenire ei, ut qui parte. someday there are going to be holidaysdsd someday there are going to be holidaysdsd someday there are going to someday there are going to be holidaysdsd someday there are going to be holidaysdsd someing to be theholidaysdsd someday there are going to be holidaysdsd someday there are going to be holidaysdsd`,
		publish_date: '04/08/23',
		readed: true,
		noticeStatus: 'New',
		type: 'approvedpending',
	},
	{
		title: 'Up-Coming Vacation Saved_Template',
		msg: 'Causae eripuit sententiae at eam, volumus adipiscing liberavisse duo ad. Has wisi invenire ei, ut qui parte.....',
		summary: `Causae eripuit sententiae at eam, volumus adipiscing liberavisse duo ad.Has wisi invenire ei, ut qui parte. someday there are going to be holidaysdsd someday there are going to be holidaysdsd someday there are going to someday there are going to be holidaysdsd someday there are going to be holidaysdsd someing to be theholidaysdsd someday there are going to be holidaysdsd someday there are going to be holidaysdsd`,
		publish_date: '04/08/23',
		readed: true,
		noticeStatus: 'New',
		type: 'savedtemplate',
	},
	{
		title: 'Up-Coming Vacation Draft ',
		msg: 'Causae eripuit sententiae at eam, volumus adipiscing liberavisse duo ad. Has wisi invenire ei, ut qui parte.....',
		summary: `Causae eripuit sententiae at eam, volumus adipiscing liberavisse duo ad.Has wisi invenire ei, ut qui parte. someday there are going to be holidaysdsd someday there are going to be holidaysdsd someday there are going to someday there are going to be holidaysdsd someday there are going to be holidaysdsd someing to be theholidaysdsd someday there are going to be holidaysdsd someday there are going to be holidaysdsd`,
		publish_date: '04/08/23',
		readed: true,
		noticeStatus: 'New',
		type: 'draft',
	},
	{
		title: 'Up-Coming Vacation Draft ',
		msg: 'Causae eripuit sententiae at eam, volumus adipiscing liberavisse duo ad. Has wisi invenire ei, ut qui parte.....',
		summary: `Causae eripuit sententiae at eam, volumus adipiscing liberavisse duo ad.Has wisi invenire ei, ut qui parte. someday there are going to be holidaysdsd someday there are going to be holidaysdsd someday there are going to someday there are going to be holidaysdsd someday there are going to be holidaysdsd someing to be theholidaysdsd someday there are going to be holidaysdsd someday there are going to be holidaysdsd`,
		publish_date: '04/08/23',
		readed: true,
		noticeStatus: 'Expiring soon',
		type: 'draft',
	},
	{
		title: 'Up-Coming Vacation Draft ',
		msg: 'Causae eripuit sententiae at eam, volumus adipiscing liberavisse duo ad. Has wisi invenire ei, ut qui parte.....',
		summary: `Causae eripuit sententiae at eam, volumus adipiscing liberavisse duo ad.Has wisi invenire ei, ut qui parte. someday there are going to be holidaysdsd someday there are going to be holidaysdsd someday there are going to someday there are going to be holidaysdsd someday there are going to be holidaysdsd someing to be theholidaysdsd someday there are going to be holidaysdsd someday there are going to be holidaysdsd`,
		publish_date: '04/08/23',
		readed: true,
		noticeStatus: 'Expiring soon',
		type: 'draft',
	},
	{
		title: 'Up-Coming Vacation Expired',
		msg: 'Causae eripuit sententiae at eam, volumus adipiscing liberavisse duo ad. Has wisi invenire ei, ut qui parte.....',
		summary: `Causae eripuit sententiae at eam, volumus adipiscing liberavisse duo ad.Has wisi invenire ei, ut qui parte. someday there are going to be holidaysdsd someday there are going to be holidaysdsd someday there are going to someday there are going to be holidaysdsd someday there are going to be holidaysdsd someing to be theholidaysdsd someday there are going to be holidaysdsd someday there are going to be holidaysdsd`,
		publish_date: '04/08/23',
		readed: true,
		noticeStatus: 'New',
		type: 'expired',
	},
	{
		title: 'Up-Coming Vacation Expired',
		msg: 'Causae eripuit sententiae at eam, volumus adipiscing liberavisse duo ad. Has wisi invenire ei, ut qui parte.....',
		summary: `Causae eripuit sententiae at eam, volumus adipiscing liberavisse duo ad.Has wisi invenire ei, ut qui parte. someday there are going to be holidaysdsd someday there are going to be holidaysdsd someday there are going to someday there are going to be holidaysdsd someday there are going to be holidaysdsd someing to be theholidaysdsd someday there are going to be holidaysdsd someday there are going to be holidaysdsd`,
		publish_date: '04/08/23',
		readed: true,
		noticeStatus: 'Expiring soon',
		type: 'expired',
	},
	{
		title: 'Up-Coming Vacation Expired',
		msg: 'Causae eripuit sententiae at eam, volumus adipiscing liberavisse duo ad. Has wisi invenire ei, ut qui parte.....',
		summary: `Causae eripuit sententiae at eam, volumus adipiscing liberavisse duo ad.Has wisi invenire ei, ut qui parte. someday there are going to be holidaysdsd someday there are going to be holidaysdsd someday there are going to someday there are going to be holidaysdsd someday there are going to be holidaysdsd someing to be theholidaysdsd someday there are going to be holidaysdsd someday there are going to be holidaysdsd`,
		publish_date: '04/08/23',
		readed: true,
		noticeStatus: 'New',
		type: 'expired',
	},
];
const buttonArray = [
	{
		title: 'All',
		isActive: true,
	},
	{
		title: 'New',
		isActive: false,
	},
	{
		title: 'Expiring soon',
		isActive: false,
	},
];

export { noticeArray, buttonArray };
